#!/usr/bin/env node
// Turn the frozen dashboard into a config-driven one, without editing the
// frozen file.
//
//   node tools/contract/parameterize.mjs --write    regenerate generated/
//   node tools/contract/parameterize.mjs --check    fail if generated/ is stale
//
// Every edit below is ANCHORED on an exact string from `upstream/dashboard.js`
// and must match exactly once. If upstream changes that string, this refuses
// rather than patching the wrong place, which is the difference between a
// vendored copy and the port in `tools/charts/chart.mjs` that quietly diverged.
// `sync-contract.sh --check` catches the same drift one step earlier; this is
// the second line.
//
// Each edit replaces a hard-coded literal with `__cfg('<path>', <the same
// literal>)`. With no config present every read returns the literal, so the
// generated file behaves exactly as the frozen one does. `golden-render.test.mjs`
// proves that by rendering both and comparing the HTML byte for byte, and that
// is the property that makes this parameterisation safe to offer upstream: it
// changes nothing about causl's own page.
//
// Config reaches the browser as a synchronous global, set by a `<script>` before
// this file loads:
//
//   <script>window.LIBVIPRS_BENCH_CONFIG = { ... }</script>
//   <script src="./dashboard.js"></script>
//
// Synchronous because the constants are evaluated the moment the IIFE runs, so
// there is no await to hang a fetch on, and a page that renders causl's defaults
// for 200ms and then swaps them is worse than one that never had them.
//
// Exit codes: 0 ok · 1 stale (--check) · 2 usage · 3 refused (an anchor moved)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const FROZEN = join(here, 'upstream', 'dashboard.js');
const OUT_DIR = join(here, 'generated');
const OUT = join(OUT_DIR, 'dashboard.js');
const REV_FILE = join(here, 'UPSTREAM_REV');

const EXIT = { OK: 0, STALE: 1, USAGE: 2, REFUSED: 3 };

// ---------------------------------------------------------------------------
// The preamble. Self-contained: a flat static site loads this as one <script>,
// so it can import nothing.
// ---------------------------------------------------------------------------

const PREAMBLE_BEGIN = '  /* ==== libviprs contract preamble: BEGIN (generated, not upstream) ==== */';
const PREAMBLE_END = '  /* ==== libviprs contract preamble: END ==== */';

const PREAMBLE = `${PREAMBLE_BEGIN}
  /* Generated by tools/contract/parameterize.mjs from tools/contract/upstream/
     dashboard.js. Do not edit this file: edit config.json, or the parameteriser.

     Every constant below this block reads through __cfg(path, literal). The
     literal is causl's, unchanged, so with no config present this file is
     behaviourally identical to the frozen one. */

  const __CONFIG =
    (typeof globalThis !== 'undefined' && globalThis.LIBVIPRS_BENCH_CONFIG) || null

  /** One dotted path out of the config, or the upstream literal. Objects and
   *  arrays REPLACE the literal rather than merging into it: a merge would
   *  leave causl's series ids sitting in libviprs's plot order, which is the
   *  shape of bug that is hardest to see on a page that still renders. */
  function __cfg(path, fallback) {
    if (__CONFIG === null || typeof __CONFIG !== 'object') return fallback
    let node = __CONFIG
    for (const seg of path.split('.')) {
      if (node === null || typeof node !== 'object' || !(seg in node)) return fallback
      node = node[seg]
    }
    return node === null || node === undefined ? fallback : node
  }

  /** A sample that says it was measured but not gated gets no verdict. A
   *  verdict chip is a claim that a threshold ruled on the number, and when
   *  nothing gated the cell no threshold did. Only the literal \`false\` counts:
   *  absent or null means nobody said, which is a different fact.
   *
   *  Off unless config turns it on, and off is upstream's behaviour exactly. */
  function __gateVerdict(sample) {
    if (!__cfg('verdict.gate.enabled', false)) return null
    const field = __cfg('verdict.gate.field', 'gated')
    if (!sample || sample[field] !== false) return null
    return {
      kind: __cfg('verdict.gate.kind', 'ungated'),
      detail: __cfg('verdict.gate.label', 'measured, not gated'),
    }
  }

  /** A delta smaller than this cell's own replicate spread is noise: not a
   *  pass, not a regression, not an improvement. The first full libviprs
   *  capture measured a median replicate spread of 3.46% across 48 metrics
   *  with one metric at 53.3%, so a 20% delta on that metric is what an idle
   *  machine produces, and ruling it a regression invents a result.
   *
   *  A sample carrying no measured spread does not fall through to the
   *  thresholds by default: \`onMissingSpread: 'unknown'\` refuses to rule,
   *  because a spread that was not measured is not a spread. \`'skip'\` is the
   *  upstream behaviour, and upstream is the default.
   *
   *  \`spread\` is a PERCENT (3.46 means 3.46%); \`delta\` is a fraction. */
  function __noiseVerdict(sample, delta, detail) {
    if (!__cfg('verdict.noise.enabled', false)) return null
    const field = __cfg('verdict.noise.spreadField', 'replicateSpreadPct')
    const raw = sample ? sample[field] : null
    const kind = __cfg('verdict.noise.kind', 'noise')
    if (!Number.isFinite(raw)) {
      if (__cfg('verdict.noise.onMissingSpread', 'skip') === 'unknown') {
        return {
          kind: 'unknown',
          detail:
            detail +
            ', and this cell carries no measured replicate spread, so there is nothing to ' +
            'tell a real move from noise',
        }
      }
      return null
    }
    const floor = __cfg('verdict.noise.floorPct', null)
    const spreadPct = Number.isFinite(floor) ? Math.max(raw, floor) : raw
    if (Math.abs(delta) * 100 > spreadPct) return null
    return {
      kind,
      detail: detail + ', inside this cell\\'s ' + formatNumber(spreadPct) + '% replicate spread',
    }
  }

  /** The legend's verdict slot. Kinds listed in \`verdict.noChipKinds\` render
   *  their label as plain text instead of a chip, because a chip is the page's
   *  way of saying a threshold ruled. Empty upstream, so upstream gets exactly
   *  the chip it has always emitted, character for character. */
  function __verdictChip(verdict) {
    const noChip = __cfg('verdict.noChipKinds', [])
    if (Array.isArray(noChip) && noChip.includes(verdict.kind)) {
      return (
        \`<span class="bench-legend-measured" title="\${escapeHtml(verdict.detail)}">\` +
        \`<span class="bench-legend-measured-label">\${escapeHtml(verdict.detail)}</span>\` +
        \`</span>\`
      )
    }
    return (
      \`<span class="bench-legend-verdict" title="\${escapeHtml(verdict.detail)}">\` +
      \`<span class="bench-legend-verdict-dot" aria-hidden="true"></span>\` +
      \`<span class="bench-legend-verdict-label">\${verdict.kind}</span>\` +
      \`</span>\`
    )
  }

  /** The fields a chart point carries out of its sample.
   *
   *  \`groupSections\` builds a fixed-shape point object and that object is the
   *  ONLY thing \`computeVerdict\` ever sees, so a rule that reads a sample field
   *  reads nothing unless the field is carried across here. With no config the
   *  list is empty and the spread adds nothing, so upstream's point object is
   *  unchanged down to its key order.
   *
   *  The two verdict rules add their own field automatically when they are on,
   *  because a rule that silently reads undefined is worse than one that is
   *  off. \`samples.carry\` is for everything else the page wants to keep, such
   *  as a metric's unit and direction. */
  function __carryFields(sample) {
    const extra = __cfg('samples.carry', [])
    const wanted = Array.isArray(extra) ? [...extra] : []
    if (__cfg('verdict.noise.enabled', false)) {
      wanted.push(__cfg('verdict.noise.spreadField', 'replicateSpreadPct'))
    }
    if (__cfg('verdict.gate.enabled', false)) {
      wanted.push(__cfg('verdict.gate.field', 'gated'))
    }
    if (wanted.length === 0) return {}
    const out = {}
    for (const f of wanted) if (f in sample) out[f] = sample[f]
    return out
  }

  /** What makes two runs the same era, as a comparable string, or null when the
   *  entry carries no claim at all.
   *
   *  Upstream breaks an era on the measured library set and nothing else, which
   *  is right when every run comes off one CI machine. libviprs runs are taken
   *  on whatever host is to hand, so the host fingerprint and the filesystem
   *  type are axes too: otherwise a run on a different machine draws a line
   *  across two machines and the step between them reads as a regression.
   *
   *  With the default single library-set axis this returns null for an entry
   *  with no samples and a sorted id list otherwise, which is exactly what
   *  upstream's libsOf/sameLibs pair decided. */
  function __eraSignature(entry) {
    const axes = __cfg('era.axes', [{ id: 'series', from: 'samples[].library', kind: 'set' }])
    const pluck = (node, path) => {
      let nodes = [node]
      for (const raw of path.split('.')) {
        const splat = raw.endsWith('[]')
        const seg = splat ? raw.slice(0, -2) : raw
        const next = []
        for (const n of nodes) {
          if (n === null || typeof n !== 'object') continue
          const v = n[seg]
          if (v === undefined || v === null) continue
          if (splat) {
            if (Array.isArray(v)) next.push(...v)
          } else {
            next.push(v)
          }
        }
        nodes = next
      }
      return nodes
    }
    const parts = []
    let anyClaim = false
    for (const axis of axes) {
      const vals = pluck(entry, axis.from)
      if (vals.length > 0) anyClaim = true
      const shown =
        axis.kind === 'set'
          ? [...new Set(vals.map(String))].sort()
          : vals.map(String)
      parts.push(axis.id + '=' + shown.join('\\u0001'))
    }
    return anyClaim ? parts.join('\\u0002') : null
  }
${PREAMBLE_END}
`;

// ---------------------------------------------------------------------------
// Anchored edits
// ---------------------------------------------------------------------------

/** A constant whose initializer is a bracketed literal: anchor on the exact
 *  declaration prefix, then take the balanced literal that follows and wrap it.
 *  Comments inside the literal (LIBRARY_COLOR has one per line) survive, which
 *  is the point of wrapping rather than rewriting. */
const wrap = (id, open, path) => ({ kind: 'wrap', id, open, path });
/** A constant whose initializer is a scalar running to end of line. */
const scalar = (id, open, path) => ({ kind: 'scalar', id, open, path });
/** An exact string swap. */
const swap = (id, find, replace) => ({ kind: 'swap', id, find, replace });

const EDITS = [
  swap(
    'preamble',
    "(() => {\n  'use strict'\n",
    `(() => {\n  'use strict'\n\n${PREAMBLE}`,
  ),

  wrap('LIBRARY_ORDER', '  const LIBRARY_ORDER = ', 'series.order'),
  wrap('LIBRARY_LABEL', '  const LIBRARY_LABEL = ', 'series.label'),
  wrap('LIBRARY_ANNOTATION', '  const LIBRARY_ANNOTATION = ', 'series.annotation'),
  wrap('LIBRARY_COLOR', '  const LIBRARY_COLOR = ', 'series.color'),
  wrap('LIBRARY_DASH', '  const LIBRARY_DASH = ', 'series.dash'),
  wrap('DEFAULT_LIBRARIES', '  const DEFAULT_LIBRARIES = new Set(', 'defaults.libraries'),
  wrap('DEFAULT_SCALES', '  const DEFAULT_SCALES = new Set(', 'defaults.scales'),
  wrap('VERDICT_COLOR', '  const VERDICT_COLOR = ', 'verdict.color'),

  scalar('REGRESSION_PCT', '  const REGRESSION_PCT = ', 'verdict.regressionPct'),
  scalar('IMPROVED_PCT', '  const IMPROVED_PCT = ', 'verdict.improvedPct'),
  scalar('PASS_PCT', '  const PASS_PCT = ', 'verdict.passPct'),
  scalar('NOISY_PROXY', '  const NOISY_PROXY = ', 'verdict.noisyProxy'),

  // The gate behaviour. After the non-finite check, because "measured, not
  // gated" is a lie about a cell whose median is not a number.
  swap(
    'gate-check',
    `    const last = points[points.length - 1]
    if (!Number.isFinite(last.medianMs)) {
      return { kind: 'unknown', detail: 'last median is non-finite' }
    }
`,
    `    const last = points[points.length - 1]
    if (!Number.isFinite(last.medianMs)) {
      return { kind: 'unknown', detail: 'last median is non-finite' }
    }

    // libviprs (config-gated, inert upstream): a cell that was measured but
    // not gated gets no verdict at all.
    const __ungated = __gateVerdict(last)
    if (__ungated) return __ungated
`,
  ),

  // The noise behaviour, ahead of the regression and improvement lines: a
  // metric whose replicate spread is 53.3% clears a 10% threshold from nothing.
  swap(
    'noise-check',
    `    if (delta > REGRESSION_PCT) return { kind: 'regressed', detail }`,
    `    // libviprs (config-gated, inert upstream): a delta inside this cell's
    // own replicate spread is noise, and it is decided before the thresholds
    // below because those thresholds cannot tell one from a real move.
    const __noise = __noiseVerdict(last, delta, detail)
    if (__noise) return __noise

    if (delta > REGRESSION_PCT) return { kind: 'regressed', detail }`,
  ),

  // The chart point's shape. Without this the verdict rules read fields that
  // `groupSections` never copied out of the sample, which looks exactly like a
  // rule that is off.
  swap(
    'carry-fields',
    `          boundaryCrossings: sample.boundaryCrossings,
          boundaryBytes: sample.boundaryBytes,
        })`,
    `          boundaryCrossings: sample.boundaryCrossings,
          boundaryBytes: sample.boundaryBytes,
          // libviprs (config-gated, inert upstream): the fields the verdict
          // rules read live on the sample, and this object is the only thing
          // computeVerdict ever sees.
          ...__carryFields(sample),
        })`,
  ),

  // The legend's verdict slot.
  swap(
    'verdict-chip',
    `        \`<span class="bench-legend-verdict" title="\${escapeHtml(verdict.detail)}">\` +
        \`<span class="bench-legend-verdict-dot" aria-hidden="true"></span>\` +
        \`<span class="bench-legend-verdict-label">\${verdict.kind}</span>\` +
        \`</span>\` +`,
    `        __verdictChip(verdict) +`,
  ),

  // The era axes.
  swap(
    'era-axes',
    `    const libsOf = (e) => {
      const set = new Set()
      for (const smp of e.samples ?? []) if (smp.library) set.add(smp.library)
      return set
    }
    const sameLibs = (a, b) => a.size === b.size && [...a].every((l) => b.has(l))
    // Walk back from the newest run while the library set is unchanged.
    const latest = libsOf(history[history.length - 1])
    if (latest.size === 0) return 0
    let start = history.length - 1
    while (start > 0) {
      const prev = history[start - 1]
      // Entries with no samples at all carry no library claim; step
      // over them rather than letting one end the era.
      const prevLibs = libsOf(prev)
      if (prevLibs.size > 0 && !sameLibs(prevLibs, latest)) break
      start -= 1
    }
    return start`,
    `    // Walk back from the newest run while the era signature is unchanged.
    // With the default single library-set axis this is upstream's comparison
    // exactly; libviprs adds the host fingerprint and the filesystem type so a
    // run on a different machine starts a new era.
    const latest = __eraSignature(history[history.length - 1])
    if (latest === null) return 0
    let start = history.length - 1
    while (start > 0) {
      // Entries carrying no claim on any axis step over rather than ending
      // the era, which is what an empty \`samples\` did upstream.
      const prev = __eraSignature(history[start - 1])
      if (prev !== null && prev !== latest) break
      start -= 1
    }
    return start`,
  ),
];

// ---------------------------------------------------------------------------

class AnchorMoved extends Error {}

function countOf(hay, needle) {
  let n = 0;
  let i = hay.indexOf(needle);
  while (i !== -1) {
    n += 1;
    i = hay.indexOf(needle, i + needle.length);
  }
  return n;
}

/** Span of the bracketed literal starting at `from`, skipping strings, template
 *  literals, regexes-by-proxy and comments. Returns the index one past its
 *  closing bracket. */
export function balancedEnd(src, from) {
  const open = src[from];
  const close = { '{': '}', '[': ']', '(': ')' }[open];
  if (!close) throw new AnchorMoved(`expected a bracketed literal at offset ${from}, found ${JSON.stringify(open)}`);
  let depth = 0;
  for (let i = from; i < src.length; i += 1) {
    const c = src[i];
    if (c === '/' && src[i + 1] === '/') {
      i = src.indexOf('\n', i);
      if (i === -1) break;
      continue;
    }
    if (c === '/' && src[i + 1] === '*') {
      i = src.indexOf('*/', i) + 1;
      continue;
    }
    if (c === "'" || c === '"' || c === '`') {
      const q = c;
      i += 1;
      while (i < src.length && src[i] !== q) {
        if (src[i] === '\\') i += 1;
        i += 1;
      }
      continue;
    }
    if (c === open) depth += 1;
    else if (c === close) {
      depth -= 1;
      if (depth === 0) return i + 1;
    }
  }
  throw new AnchorMoved(`unbalanced ${open} starting at offset ${from}`);
}

export function parameterize(src) {
  let out = src;
  const applied = [];
  for (const edit of EDITS) {
    if (edit.kind === 'swap') {
      const n = countOf(out, edit.find);
      if (n !== 1) {
        throw new AnchorMoved(
          `edit "${edit.id}": its anchor matches ${n} times in dashboard.js, not once. ` +
            'Upstream moved; re-pin and re-anchor rather than patching the wrong place.',
        );
      }
      out = out.replace(edit.find, () => edit.replace);
      applied.push(edit.id);
      continue;
    }

    const n = countOf(out, edit.open);
    if (n !== 1) {
      throw new AnchorMoved(
        `edit "${edit.id}": the declaration ${JSON.stringify(edit.open)} matches ${n} times, not once`,
      );
    }
    const at = out.indexOf(edit.open) + edit.open.length;
    let end;
    if (edit.kind === 'wrap') {
      end = balancedEnd(out, at);
    } else {
      const nl = out.indexOf('\n', at);
      const cm = out.indexOf('//', at);
      end = cm !== -1 && cm < nl ? cm : nl;
      while (end > at && out[end - 1] === ' ') end -= 1;
    }
    const literal = out.slice(at, end);
    out = `${out.slice(0, at)}__cfg('${edit.path}', ${literal})${out.slice(end)}`;
    applied.push(edit.id);
  }
  return { out, applied };
}

/** Every path the generated file reads, for the schema and the tests. */
export const CONFIG_PATHS = EDITS.filter((e) => e.path).map((e) => e.path).concat([
  'verdict.noise.enabled',
  'verdict.noise.kind',
  'verdict.noise.spreadField',
  'verdict.noise.onMissingSpread',
  'verdict.noise.floorPct',
  'verdict.gate.enabled',
  'verdict.gate.field',
  'verdict.gate.kind',
  'verdict.gate.label',
  'verdict.noChipKinds',
  'era.axes',
  'samples.carry',
]);

// --- CLI --------------------------------------------------------------------

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const argv = process.argv.slice(2);
  const mode = argv.includes('--write') ? 'write' : argv.includes('--check') ? 'check' : null;
  if (!mode) {
    console.error('usage: parameterize.mjs (--check | --write)');
    process.exit(EXIT.USAGE);
  }

  const rev = readFileSync(REV_FILE, 'utf8').trim();
  const src = readFileSync(FROZEN, 'utf8');
  let result;
  try {
    result = parameterize(src);
  } catch (err) {
    if (err instanceof AnchorMoved) {
      console.error(`parameterize: refused, ${err.message}`);
      process.exit(EXIT.REFUSED);
    }
    throw err;
  }

  const banner =
    `/* GENERATED from tools/contract/upstream/dashboard.js (causl-org @ ${rev})\n` +
    `   by tools/contract/parameterize.mjs. Do not edit: change config.json, or\n` +
    `   the parameteriser, and re-run \`parameterize.mjs --write\`.\n` +
    `   Edits applied: ${result.applied.join(', ')} */\n`;
  const next = banner + result.out;

  if (mode === 'write') {
    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(OUT, next);
    console.log(`parameterize: wrote ${OUT} (${result.applied.length} edits)`);
    process.exit(EXIT.OK);
  }

  if (!existsSync(OUT)) {
    console.error(`parameterize: STALE, ${OUT} does not exist. Run --write.`);
    process.exit(EXIT.STALE);
  }
  if (readFileSync(OUT, 'utf8') !== next) {
    console.error(`parameterize: STALE, ${OUT} is not what the frozen file and this script produce.`);
    console.error('              Run --write. Do not hand-edit generated/.');
    process.exit(EXIT.STALE);
  }
  console.log(`parameterize: generated/dashboard.js is current (${result.applied.length} edits)`);
  process.exit(EXIT.OK);
}
